### PR TITLE
hooks: Migrate fetching logic into React Hooks

### PR DESCRIPTION
**Pull request by jonathankingfc**
- This PR moves a lot of fetching logic being called in components into separate React Hooks
- These react hooks fetch information from the backend through the React Query library, which caches results and performs background fetching

### CODE REVIEW

**Review by bcaton85 — COMMENTED** [review]
Left a few comments. Good direction, the separation of request vs rendering logic is really nice. While doing some local testing I found the following issues that should be addressed:

Org List page
- Members field is stuck in the loading state, not seeing the request being made. Most likely because it is the user namespace? Are default values set for these fields?
- Network tab shows 4 calls to `superuser/organizations` even though `FEATURE_SUPERUSERS_FULL_ACCESS` is set to `false`
- Setting `FEATURE_SUPERUSERS_FULL_ACCESS: true` breaks the org list page.
- Error handling modals no longer working for creating and deleting orgs

Repositories List
- Changing visibility and creating repositories no longer updates the list. Have to manually reload page to get latest values
- Error handling no longer works for creating and deleting repos

Overall looks good though. I'll use the same pattern in future PR's

**Comment by bcaton85** [comment]
Gave this another run through. Some have been fixed but still seeing these issues:
- Other user namespaces are not appearing in the Org list when `FEATURE_SUPERUSER_FULL_ACCESS: true`
- API's that respond with `4XX` seem to be retried every few seconds (Possibly also due to `refetchOnWindowFocus: true`?)
- Error modal for deleting organizations doesn't seem to appear
- Changing visibility in repository list doesn't seem to update automatically, need to refresh the page
- Error modal for deleting repository doesn't seem to appear
- There's an API call to `/members` that fails with a 404 for user organizations that causes the field to get stuck on the loading skeleton after a few seconds

**Comment by jonathankingfc** [comment]
I've addressed each of the listed concerns in a separate commit for readability.

**Comment by bcaton85** [comment]
Looks good, just getting the following error trying to render the org list when `FEATURE_SUPERUSERS_FULL_ACCESS: true`, looks like default arrays for the superuser calls just need to be set.
image
Also tests for search seem to be failing for the repo list for some reason.

**Review by bcaton85 — APPROVED** [review]
LGTM

**Pull request merged**
