### PR TITLE
Replace mock columns from org table with new valid columns (PROJQUAY-4082)

### PR DESCRIPTION
**Pull request by syed**
image

### CODE REVIEW

**Comment by syed** [comment]
Orgs are sorted by last modified now

**Comment by bcaton85** [comment]
Encountered error testing it out. It seems the username is being added to the list of organization names that is passed too `fetchAllOrgs`. When it tries looking up a user namespace with the organizations endpoint it returns a 404 and prevents the table from loading. From the network tab:
image

**Comment by syed** [comment]
@bcaton85 fixed it

**Comment by bcaton85** [comment]
Code looks good and I'm able to view the organizations with details but found some regressions in behavior:
- Loading spinner no longer works, defaults to empty organization list screen before rendering table
- When creating an org the list is no longer updated. I can't find the org until i reload the screen
- When deleting orgs:
    - It seems to try to delete the same org twice, causing a 404 error
    - The error modal no longer appears on failure
    - The list is no longer updated, the org just deleted still appears in the list

**Comment by HammerMeetNail** [comment]
Performance also nose dives. The old angular UI loads all orgs within about ~2.5 seconds. `main` on `quay-ui` loads orgs in ~2 seconds and this PR loads orgs in 5.5-7.5 seconds.

**Review by bcaton85 — APPROVED** [review]
LGTM

**Pull request merged**
