### PR TITLE
Add packages tab to tag details

### PR DESCRIPTION
**Pull request by syed**
Adds packages tab to tag details

image

### CODE REVIEW

**Comment by HammerMeetNail** [comment]
What do you think about changing the chart? Right now we're showing total packages and coloring in vulnerabilities. This is a little confusing because the total number of packages might not match the number of vulnerabilities. 

This is with `alpine:3.13`. There are 14 packages but busybox has multiple vulnerabilities of different types. 
image

Maybe we should keep the total packages in the title, but the pie chart should show total number of vulnerabilities?

**Comment by syed** [comment]
Not sure I understand. You are saying to have the graph show the number of vulnerabilities instead of vulnerable packages? How would this be different from the vulnerabilities graph we have on the Security report tab

**Comment by HammerMeetNail** [comment]
Let's use the alpine pie chart as an example. If you add up all the vulnerabilities, there's 15. We add those to the pie chart but then in the center we say 14 (packages). We're drawing vulnerabilities but stating packages. There's nothing showing the sum of the vulnerabilities. The number inside the chart should be the total number of vulnerabilities since that's what's being depicted.

**Comment by syed** [comment]
Are you saying we are double counting packages? I see a problem where we have a single package which has a `High` and a `Medium` vulnerability we will end up counting that package twice

**Comment by syed** [comment]
I think the idea of this chart is to have an answer to "How many packages do I have which have X level vulnerabilitiles"

I've update the total count to reflect that now

**Comment by HammerMeetNail** [comment]
I _think_ this change will address what I'm talking about. I saw the chart as trying to answer a different question: "How many vulnerabilities do I have across x packages?". I thought this since the chart is being populated by vulnerability data. When we fill in the chart we include the double counts, so we show both the high and mid vulnerabilities in the same package. But we exclude the double counts from the total shown in the chart.

**Comment by syed** [comment]
Yeah, the latest commit should fix that

**Comment by HammerMeetNail** [comment]
Perfect, that does fix it. Looks good. I'll approve in just a sec. As a general comment, it would be nice to see some more comments, especially around functions. Most of the code is pretty self-evident, but they can still be helpful.

**Pull request merged**
