### PR TITLE
Building Breadcrumbs by keeping track of browser history (PROJQUAY-4090)

### PR DESCRIPTION
**Pull request by Sunandadadi**
Breadcrumbs are generated by two ways:

1. From url route
2. From Browser history

If the browser history is empty, breadcrumbs will be generated from the url route. If browser history exists, breadcrumbs are generated from this history. `BrowserHistoryState` tracks users history on the application.

### CODE REVIEW

**Comment by HammerMeetNail** [comment]
@Sunandadadi Is this ready for review? Can you rebase main?

**Comment by HammerMeetNail** [comment]
Breadcrumbs are working, but there's a couple spots that should be looked at more. 

1. It looks like the entire page is re-rendering when clicking on `organizations`, `repositories`, or `<repoName>` breadcrumbs. This causes the entire screen to flash white for a brief moment before showing the page content. The first two are known issues that @bcaton85 is working to fix. This PR introduces the re-render for `<repoName>`. Maybe they're all related?

The expected behavior should be like in the security report. If you click on the `<tagName>` breadcrumb, that renders only the content in the body, making for a smooth experience. The rest of the links should behave this way too. 

2. `organizations` to `<orgName>` makes sense, but then if you select a `<repoName>` the root of the tree changes from `organizations` to `repositories`. Breadcrumbs then can't be used to go back to `organizations`. Similarly, refreshing a tag always sets the breadcrumbs to be  under `repositories` even if the user navigated there from `organizations`. It's probably not a big deal since `organizations` is right there on the navbar, but is there a way to be more consistent? This is one of those things that will flash a change whenever someone selects a repo.

**Comment by bcaton85** [comment]
> This causes the entire screen to flash white for a brief moment before showing the page content. 

As an FYI this is because the top level Suspense in `StandaloneMain` is being triggered by recoil, which replaces the whole page with the loading icon. I've resolved this in a future PR by catching the loading action within the org and repo components.

**Comment by Sunandadadi** [comment]
The issues in the mentioned comments should be fixed. Added state persistence using recoil-persist.

**Review by HammerMeetNail — APPROVED** [review]
LGTM

**Pull request merged**
