### PR TITLE
Use loading page while waiting on security report (PROJQUAY-4152)

### PR DESCRIPTION
**Pull request by HammerMeetNail**
* Adds Spinners to tables to indicate loading
* Adds Skeleton to Tag table cells to indicate loading
* Adds Skeleton to Tag Details and Security Report pages. 

This can best be tested by throttling the network connection using either Firefox and [GPRS throttling](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/throttling/index.html) or Chrome and [url-throttler](https://chrome.google.com/webstore/detail/url-throttler/kpkeghonflnkockcnaegmphgdldfnden)

### CODE REVIEW

**Comment by HammerMeetNail** [comment]
Wondering if there are any other spots that should have some kind of loading indicator? Details looks like it load instantly. Maybe the security report cell while we're waiting on scan status?

**Comment by syed** [comment]
I believe we agreed on using a Skeleton https://www.patternfly.org/v4/components/skeleton/react

**Comment by bcaton85** [comment]
Any where an api response is called. Off the top of my head there is the following. (Loading has been already implemented for some of these) (These are only the components that I've worked on that have API calls)
- src/routes/RepositoryDetails/Tags/SecurityDetails.tsx
- src/components/labels/Labels.tsx
- src/routes/RepositoryDetails/Tags/Tags.tsx
- src/routes/TagDetails/TagDetails.tsx
- src/routes/RepositoryDetails/Tags/DeleteModal.tsx

If we could artificially add delay we could see what parts of the ui are effected. Maybe in the mock responses?

**Comment by syed** [comment]
you could use this https://chrome.google.com/webstore/detail/url-throttler/kpkeghonflnkockcnaegmphgdldfnden

**Comment by bcaton85** [comment]
Everything looks good. Except I think we're going to need a check when the security state is `queued`. Currently if the security endpoint responds with `queued` the loading screens don't disappear, giving the impression it's waiting for a network response when really it did respond, it just doesn't know what to do with the `queued` state. 

We'll need to display some content saying that the scanning hasn't produced any results yet. Not sure if we want to fix this in this PR or a future PR. Maybe we add some place holder for now. What are your thoughts?

**Comment by HammerMeetNail** [comment]
@bcaton85 Let's catch it in a follow up PR.

**Review by bcaton85 — APPROVED** [review]
LGTM

**Pull request merged**
